FROM eclipse-temurin:17-jdk-focal AS builder

# Leiningen
RUN curl -sSL https://raw.githubusercontent.com/technomancy/leiningen/2.9.10/bin/lein > /usr/local/bin/lein && \
    chmod 755 /usr/local/bin/lein

# avoid tzdata installation starting to ask questions
ARG DEBIAN_FRONTEND=noninteractive

# PostgreSQL
RUN apt-get update && \
    apt-get install -y gnupg && \
    echo 'deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main' > /etc/apt/sources.list.d/pgdg.list  && \
    curl -SL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-13 postgresql-13-postgis-3 sudo && \
    rm -rf /var/lib/apt/lists/*

# working directory
RUN mkdir -p /project
WORKDIR /project

# cache Leiningen dependencies
COPY project.clj /project/
RUN lein deps

# source code
COPY resources /project/resources
COPY test /project/test
COPY src /project/src
COPY src-java /project/src-java

# run tests
COPY test-config.edn tests.edn postgres-init.sql /project/
RUN service postgresql start && \
    sudo -u postgres psql -c "CREATE USER territorybro WITH CREATEROLE PASSWORD 'territorybro';" && \
    sudo -u postgres psql -c "CREATE DATABASE territorybro OWNER territorybro;" && \
    sudo -u postgres psql -d territorybro -f postgres-init.sql && \
    lein kaocha && \
    service postgresql stop

# build the binary
RUN lein uberjar

# prepare AppCDS class list
RUN service postgresql start && \
    java -XX:DumpLoadedClassList=classes.lst -Dconf=test-config.edn -jar "target/default+uberjar/territory-bro.jar" app-cds-setup && \
    service postgresql stop

# ------------------------------------------------------------

FROM eclipse-temurin:17-jre-focal

EXPOSE 8080
ENV PORT=8080 \
    NREPL_BIND=0.0.0.0 \
    DATABASE_URL="jdbc:postgresql://localhost/territorybro?user=territorybro&password=territorybro"

# the user should have no write permissions, even to its home
RUN adduser --no-create-home --home /app app && \
    mkdir /app
WORKDIR /app

COPY --from=builder "/project/target/default+uberjar/territory-bro.jar" /app/

# prepare AppCDS shared archive
COPY --from=builder /project/classes.lst /app/
RUN java -Xshare:dump \
        -XX:SharedClassListFile=classes.lst \
        -XX:SharedArchiveFile=classes.jsa \
        --class-path territory-bro.jar && \
    rm classes.lst

USER app
ENTRYPOINT ["java", "-Xshare:on", "-XX:SharedArchiveFile=classes.jsa", "-jar", "territory-bro.jar"]
