FROM node:18-alpine AS builder

RUN apk add findutils zopfli

# working directory
RUN mkdir -p /project && \
    chown node /project
WORKDIR /project
USER node

# cache node_modules
COPY --chown=node package.json yarn.lock /project/
RUN yarn install --frozen-lockfile --non-interactive --no-progress && \
    yarn cache clean

# do the build
COPY --chown=node tsconfig.json tsconfig.node.json vite.config.ts /project/
COPY --chown=node web /project/web
RUN yarn run test && \
    yarn run build

# offline compress static resources
RUN find /project/target/web-dist \
        -type f \
        -regextype posix-extended \
        -iregex '.*\.(html?|js|map|css|svg|otf|ttf|txt|json)' \
        -exec zopfli '{}' \;

# ------------------------------------------------------------

FROM nginx:1.16-alpine

COPY web/docker/nginx-default.conf.template /etc/nginx/conf.d/default.conf.template

COPY web/docker/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

COPY --from=builder /project/target/web-dist /usr/share/nginx/html
