FROM openjdk:11-jdk AS builder

# tools
ADD https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein /usr/local/bin/lein
RUN chmod 755 /usr/local/bin/lein

# working directory
RUN useradd --create-home app && \
    mkdir -p /project && \
    chown app /project
WORKDIR /project
USER app

# cache Leiningen dependencies
COPY --chown=app project.clj /project/
RUN lein deps

# do the build
COPY --chown=app env /project/env
COPY --chown=app resources /project/resources
COPY --chown=app test /project/test
COPY --chown=app src /project/src
COPY --chown=app src-java /project/src-java
RUN lein uberjar

# ------------------------------------------------------------

FROM openjdk:11-jre-slim

RUN adduser --system --home /app app
WORKDIR /app
USER app

EXPOSE 8080
ENV PORT=8080 \
    NREPL_BIND=0.0.0.0 \
    DATABASE_URL="jdbc:postgresql://localhost/territorybro?user=territorybro&password=territorybro"
ENTRYPOINT ["java", "-Xmx50m", "--illegal-access=deny", "-jar", "territory-bro.jar"]

COPY --from=builder /project/target/uberjar/territory-bro.jar /app/territory-bro.jar
