FROM ubuntu:latest

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		curl \
		git \
		less \
		man \
		nano \
		openjdk-8-jdk \
		wget \
	&& curl -sL https://deb.nodesource.com/setup_6.x | bash - \
	&& apt-get install -y --no-install-recommends \
		nodejs \
	&& rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --home /home/dev dev
ADD https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein /home/dev/bin/lein
RUN chmod a+x /home/dev/bin/lein
COPY docker/dev/.bash_history /home/dev/
COPY docker/dev/.npmrc /home/dev/
RUN mkdir -p /project /home/dev/.m2 /home/dev/.lein \
	&& chown -R dev:dev /project /home/dev
ENV EDITOR=nano

EXPOSE 8080

USER dev
WORKDIR /project
CMD ["bash", "--login"]
