FROM node:21-alpine AS builder

RUN apk add findutils zopfli

# working directory
RUN mkdir -p /project && \
    chown node /project
WORKDIR /project
USER node

# cache node_modules
COPY --chown=node package.json package-lock.json /project/
RUN npm ci

# do the build
COPY --chown=node tsconfig.json tsconfig.node.json vite.config.ts /project/
COPY --chown=node web /project/web
ARG VITE_GIT_COMMIT
RUN npm run test && \
    npm run build

# offline compress static resources
RUN find /project/target/web-dist/public \
        -type f \
        -regextype posix-extended \
        -iregex '.*\.(html?|js|map|css|svg|otf|ttf|txt|json)' \
        -exec zopfli '{}' \;

# ------------------------------------------------------------

FROM nginx:1.16-alpine

COPY web/docker/nginx-default.conf.template /etc/nginx/conf.d/default.conf.template

COPY web/docker/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

COPY --from=builder /project/target/web-dist/public /usr/share/nginx/html
